<script setup lang="ts">
useSeoPage('URL Shortener', 'Create trackable short links, QR codes, and clear click analytics with 247URL.', '/features')
const stories = [
  { eyebrow: 'Memorable links', title: 'Create trackable links that perform.', description: 'Turn long destinations into short links that are easier to share across campaigns and channels.', points: ['Choose a custom alias for a managed link.', 'Update its destination when plans change.', 'Keep every link together in one workspace.'], view: 'domain' as const },
  { eyebrow: 'Clear analytics', title: 'See what is working, simply and clearly.', description: 'Follow click trends and understand where visits come from without losing sight of the link itself.', points: ['Review clicks over 7, 30, or 90 days.', 'Explore referrers, devices, and browser breakdowns.', 'See approximate unique visitors with privacy-conscious counting.'], view: 'analytics' as const },
  { eyebrow: 'Link control', title: 'Stay in control of every link you share.', description: 'Keep your links useful as campaigns evolve, with controls available in your account.', points: ['Edit destinations without changing the short URL.', 'Set an expiration date when a campaign ends.', 'Disable or organize links from your dashboard.'], view: 'links' as const },
]
const features = [
  { title: 'URL Shortener', text: 'Create links that are easy to share and simple to manage.', view: 'create' as const },
  { title: 'QR Codes', text: 'Give every short link another way to be discovered.', view: 'qr' as const },
  { title: 'Analytics', text: 'Understand clicks, visitors, and traffic sources.', view: 'analytics' as const },
]
const values = [['01', 'Create', 'Short links with optional aliases'], ['02', 'Share', 'QR codes for every channel'], ['03', 'Measure', 'Click and visitor analytics'], ['04', 'Manage', 'Editable destinations and link states']]
const workflow = [['Create with confidence', 'Start with a validated destination and a concise short URL.'], ['Learn from clicks', 'Review trends and traffic sources in your dashboard.'], ['Keep control', 'Change destinations and link states as your work evolves.']]
const useCases = [['Marketing', 'Bring campaign links together.', 'Use memorable aliases and click trends to keep campaigns organized.', '↗'], ['Social media', 'Make every profile link count.', 'Share compact URLs across posts, profiles, and messages.', '◎'], ['Events', 'Connect print and digital.', 'Give attendees a QR code that opens a short destination link.', '▦']]
const faqs = [
  ['What is a URL shortener?', 'A URL shortener creates a compact link that redirects to a longer destination URL.'],
  ['How does 247URL work?', 'Paste an HTTP or HTTPS destination and 247URL creates a short URL. You can manage links from an account.'],
  ['Can I customize my short links?', 'Yes. Managed links support unique custom aliases using letters, numbers, hyphens, and underscores.'],
  ['Can I track clicks?', 'Yes. Managed links include click trends and breakdowns for referrers, devices, browsers, and more.'],
  ['Can I generate QR codes?', 'Yes. You can display a QR code for a short link in the dashboard.'],
  ['Can I edit a destination after creating a link?', 'Yes. You can update the destination of a managed link while keeping its short URL.'],
  ['Are shortened URLs permanent?', 'Links do not expire by default. Managed links can be given an expiration date or disabled.'],
  ['Can I use 247URL without an account?', 'The quick shortening form supports anonymous link creation when the operator enables it. An account is needed to manage your links.'],
]
const openFaq = ref<number | null>(0)
</script>

<template>
  <div class="product-page min-w-0 overflow-hidden bg-[#F8F9FF]">
    <section class="bg-[#0b2742] text-white"><div class="container-shell pb-28 pt-16 text-center sm:pb-36 sm:pt-20 lg:pt-24">
      <p class="text-[11px] font-bold uppercase tracking-[.2em] text-[#A5B4FC]">247URL short links</p>
      <h1 class="mx-auto mt-4 max-w-[770px] text-[clamp(2.5rem,5.5vw,4.8rem)] font-bold leading-[1.04] tracking-[-.05em]">Create trackable links that perform with our powerful URL shortener.</h1>
      <p class="mx-auto mt-5 max-w-xl text-sm leading-6 text-slate-200 sm:text-base">Shorten links, generate QR codes, and understand every click from one clear workspace.</p>
      <div class="mx-auto mt-8 max-w-[700px] text-left"><UrlShortenerForm hero /></div>
      <p class="mt-4 text-xs text-slate-300">Create a short link in seconds. No account needed when anonymous creation is enabled.</p>
    </div></section>
    <section class="relative z-10 mx-auto -mt-24 w-full max-w-[920px] px-5 sm:-mt-28 sm:px-6" aria-label="247URL dashboard preview"><MarketingProductPreview view="links" /></section>
    <section class="container-shell py-16 text-center sm:py-20"><p class="text-xs font-semibold uppercase tracking-[.12em] text-text-muted">Built for every link you share</p><div class="mx-auto mt-6 flex max-w-3xl flex-wrap items-center justify-center gap-x-9 gap-y-3 text-sm font-semibold text-[#718093]"><span>Campaigns</span><span>Social</span><span>Events</span><span>Products</span><span>Teams</span></div></section>
    <section class="container-shell pb-16 text-center sm:pb-24"><p class="eyebrow">One connected workspace</p><h2 class="mx-auto mt-3 max-w-2xl text-3xl font-bold leading-tight tracking-[-.035em] sm:text-4xl">Everything you need to make every link work harder.</h2><p class="mx-auto mt-4 max-w-xl text-sm leading-6 text-text-secondary">Create a shorter path to your content, then learn how people engage with it.</p><NuxtLink to="/register" class="btn-primary mt-6">Get started free <span aria-hidden="true">→</span></NuxtLink>
      <div class="mt-10 grid gap-4 text-left md:grid-cols-3"><article v-for="feature in features" :key="feature.title" class="flex min-w-0 flex-col overflow-hidden rounded-2xl border border-[#DCDDFC] bg-white"><div class="min-h-[230px] bg-[#EEF2FF] p-4"><MarketingProductPreview :view="feature.view" compact /></div><div class="flex flex-1 items-start justify-between gap-3 p-5"><div><h3 class="text-lg font-bold">{{ feature.title }}</h3><p class="mt-1 text-xs leading-5 text-text-secondary">{{ feature.text }}</p></div><span class="text-xl text-brand" aria-hidden="true">↗</span></div></article></div>
    </section>
    <div class="border-t border-[#DCDDFC] bg-white"><MarketingFeatureStory v-for="(story, i) in stories" :key="story.eyebrow" v-bind="story" :reverse="i === 1" /></div>
    <section class="bg-[#F5F6FF]"><div class="container-shell py-20 text-center"><p class="eyebrow">Product value</p><h2 class="mx-auto mt-3 max-w-2xl text-3xl font-bold tracking-[-.035em] sm:text-4xl">A clear view of every link.</h2><p class="mx-auto mt-4 max-w-xl text-sm leading-6 text-text-secondary">The tools you need to create, share, measure, and manage links in one place.</p><div class="mt-9 grid gap-3 text-left sm:grid-cols-2 lg:grid-cols-4"><div v-for="item in values" :key="item[0]" class="rounded-xl border border-[#DCDDFC] bg-white p-5"><p class="text-xs font-bold text-brand">{{ item[0] }}</p><h3 class="mt-4 text-lg font-bold">{{ item[1] }}</h3><p class="mt-1 text-xs leading-5 text-text-secondary">{{ item[2] }}</p></div></div></div></section>
    <section class="container-shell py-20 text-center"><p class="eyebrow">Made for your workflow</p><h2 class="mt-3 text-3xl font-bold tracking-[-.035em] sm:text-4xl">Useful for the work behind every link.</h2><p class="mx-auto mt-4 max-w-xl text-sm leading-6 text-text-secondary">From the first share to the next campaign, 247URL keeps the essentials close.</p><div class="mt-9 grid gap-4 text-left md:grid-cols-3"><article v-for="item in workflow" :key="item[0]" class="rounded-xl border border-[#DCDDFC] bg-white p-6"><span class="text-xl text-brand" aria-hidden="true">✦</span><h3 class="mt-5 text-base font-bold">{{ item[0] }}</h3><p class="mt-2 text-sm leading-6 text-text-secondary">{{ item[1] }}</p></article></div></section>
    <section class="bg-[#F5F6FF]"><div class="container-shell py-20"><div class="text-center"><p class="eyebrow">Use cases</p><h2 class="mt-3 text-3xl font-bold tracking-[-.035em] sm:text-4xl">See how teams can use 247URL.</h2></div><div class="mt-9 grid gap-4 md:grid-cols-3"><article v-for="item in useCases" :key="item[0]" class="flex min-h-[260px] flex-col overflow-hidden rounded-xl border border-[#DCDDFC] bg-white p-6"><p class="text-[10px] font-bold uppercase tracking-[.12em] text-brand">{{ item[0] }}</p><h3 class="mt-3 text-xl font-bold">{{ item[1] }}</h3><p class="mt-2 text-sm leading-6 text-text-secondary">{{ item[2] }}</p><span class="mt-auto self-end text-5xl text-brand/30" aria-hidden="true">{{ item[3] }}</span></article></div></div></section>
    <section class="container-shell py-20"><h2 class="text-center text-3xl font-bold tracking-[-.035em] sm:text-4xl">Frequently asked questions</h2><div class="mx-auto mt-9 max-w-3xl divide-y divide-[#DCDDFC] border-y border-[#DCDDFC]"><div v-for="(item, i) in faqs" :key="item[0]"><h3><button type="button" class="flex w-full items-center justify-between gap-4 py-4 text-left text-sm font-semibold" :aria-expanded="openFaq === i" :aria-controls="`feature-faq-${i}`" @click="openFaq = openFaq === i ? null : i"><span>{{ item[0] }}</span><span class="text-lg font-normal text-brand" aria-hidden="true">{{ openFaq === i ? '−' : '+' }}</span></button></h3><p v-show="openFaq === i" :id="`feature-faq-${i}`" class="max-w-2xl pb-5 text-sm leading-6 text-text-secondary">{{ item[1] }}</p></div></div></section>
    <section class="overflow-hidden bg-[#0b2742] text-white"><div class="container-shell pt-20 text-center"><p class="text-[11px] font-bold uppercase tracking-[.2em] text-[#A5B4FC]">Make every link count</p><h2 class="mt-3 text-3xl font-bold tracking-[-.04em] text-[#A5B4FC] sm:text-5xl">More than a link shortener.</h2><p class="mx-auto mt-4 max-w-xl text-sm leading-6 text-slate-200">Create links, share QR codes, and learn what connects with your audience.</p><NuxtLink to="/register" class="mt-6 inline-flex h-10 items-center gap-2 rounded-md border border-white/50 px-5 text-sm font-semibold text-white transition hover:bg-white/10">Get started free <span aria-hidden="true">→</span></NuxtLink><div class="mx-auto mt-12 max-w-[850px] translate-y-6"><MarketingProductPreview view="create" /></div></div></section>
  </div>
</template>
