<script setup lang="ts">
useSeoPage('Features', 'Create, manage, analyze, share, and automate short links with 247URL.', '/features')
const capabilities = [['Shorten','Turn long URLs into clean, memorable links.'],['Manage','Edit destinations, organize links, and control their lifecycle.'],['Analyze','Understand clicks, visitors, referrers, devices, and trends.'],['Share','Generate QR codes and distribute links across channels.'],['Automate','Use scoped API tokens to manage links programmatically.'],['Brand','Run a separate short domain through the documented deployment architecture.']]
const sections = [
  { eye:'Shorten', title:'From long and messy to clean and memorable.', copy:'Create short URLs in seconds with collision-safe generated codes or custom aliases.', points:['Secure HTTP/HTTPS validation','Custom aliases','Collision-safe short codes','Fast 302 redirects'] },
  { eye:'Manage', title:'Your links stay under your control.', copy:'Update destinations, disable links, set expiration dates, and organize tags from one workspace.', points:['Editable destinations','Active, expired, and disabled states','Tags and descriptions','Immediate cache invalidation'] },
  { eye:'Analytics', title:'Know what happens after the click.', copy:'See performance over time and understand referrers, devices, browsers, operating systems, and optional country data.', points:['7, 30, and 90 day ranges','Privacy-safe unique counts','Queued processing','Raw IP addresses are not stored'] },
]
const chart = [12,18,15,27,24,39,35,46,44,58,53,67].map((clicks,i) => ({ date: `Day ${i+1}`, clicks }))
</script>
<template><div>
  <section class="border-b border-border bg-surface"><div class="container-shell py-20 text-center"><p class="eyebrow">Everything you need to manage modern links</p><h1 class="mx-auto mt-4 max-w-3xl text-5xl font-bold leading-[1.06] tracking-[-0.035em] sm:text-6xl">Short links, without<br><span class="text-brand">the busywork.</span></h1><p class="mx-auto mt-6 max-w-2xl text-lg text-text-secondary">Create memorable short links, manage destinations, understand every click, and connect 247URL to your workflow.</p><div class="mt-8 flex justify-center gap-3"><NuxtLink to="/register" class="btn-primary btn-lg">Create a free account</NuxtLink><a href="#platform" class="btn-secondary btn-lg">Explore the platform</a></div></div></section>
  <section id="platform" class="container-shell py-20"><div class="grid gap-px overflow-hidden rounded-xl border border-border bg-border md:grid-cols-3"><article v-for="(item, i) in capabilities" :key="item[0]" class="bg-surface p-6"><span class="text-xs font-semibold text-brand">0{{ i + 1 }}</span><h2 class="mt-4 text-base font-semibold uppercase tracking-[.08em]">{{ item[0] }}</h2><p class="mt-2 text-sm text-text-secondary">{{ item[1] }}</p></article></div></section>
  <section v-for="(item, i) in sections" :key="item.eye" class="border-t border-border" :class="i % 2 ? 'bg-surface' : 'bg-canvas'"><div class="container-shell grid items-center gap-12 py-20 lg:grid-cols-2"><div :class="i % 2 ? 'lg:order-2' : ''"><p class="eyebrow">{{ item.eye }}</p><h2 class="mt-3 section-title">{{ item.title }}</h2><p class="mt-4 text-base leading-relaxed text-text-secondary">{{ item.copy }}</p><ul class="mt-6 grid gap-3 text-sm text-text-secondary"><li v-for="point in item.points" :key="point" class="flex gap-2"><span class="text-success">✓</span>{{ point }}</li></ul></div><div class="surface p-6" :class="i % 2 ? 'lg:order-1' : ''"><UrlShortenerForm v-if="i===0"/><template v-else-if="i===1"><div class="mb-4 flex items-center justify-between"><h3 class="font-semibold">Campaign links</h3><span class="text-xs text-text-muted">Illustrative preview</span></div><div v-for="row in [['summer-sale','Active'],['event-2026','Expired'],['old-offer','Disabled']]" :key="row[0]" class="flex items-center justify-between border-t border-border py-4"><div><p class="text-sm font-medium text-brand">247url.com/{{ row[0] }}</p><p class="text-xs text-text-muted">example.com/{{ row[0] }}</p></div><span :class="row[1] === 'Active' ? 'badge-success' : row[1] === 'Expired' ? 'badge-warning' : 'badge-danger'">{{ row[1] }}</span></div></template><template v-else><AnalyticsChart :points="chart"/><div class="mt-4 grid grid-cols-2 gap-3"><StatCard label="Clicks" value="12,482"/><StatCard label="Visitors" value="8,921" tone="violet"/></div></template></div></div></section>
  <section class="container-shell py-20"><div class="grid gap-8 rounded-xl border border-border bg-surface p-6 md:grid-cols-2 md:p-10"><div><p class="eyebrow">API</p><h2 class="mt-3 section-title">Build 247URL into your workflow.</h2><p class="mt-4 text-text-secondary">Create, update, and manage short links through the existing versioned API with expiring, ability-scoped tokens.</p><NuxtLink to="/dashboard/api" class="btn-secondary mt-6">Manage API tokens</NuxtLink></div><pre class="overflow-x-auto rounded-lg bg-[#111827] p-5 text-xs leading-6 text-slate-200"><code>POST /api/v1/links

{
  "destination_url":
    "https://example.com/campaign",
  "custom_alias": "summer"
}</code></pre></div></section>
  <section class="container-shell"><div class="rounded-xl bg-brand px-6 py-14 text-center text-white"><h2 class="text-3xl font-bold">Ready to build better links?</h2><p class="mt-3 text-indigo-100">Create your first short link in seconds.</p><div class="mt-7 flex justify-center gap-3"><NuxtLink to="/register" class="btn bg-white text-brand">Get started free</NuxtLink><NuxtLink to="/pricing" class="btn border border-white/30 text-white hover:bg-white/10">Explore pricing</NuxtLink></div></div></section>
</div></template>
