<script setup lang="ts">
useSeoPage('Short links. Serious results.', 'Create branded short links, manage destinations, generate QR codes, and understand every click.', '/')
const faqs = [
  ['Can I choose my own short link?', 'Yes. Authenticated users can set a unique custom alias. Anonymous shortening also supports aliases when the operator enables anonymous creation.'],
  ['Do short links expire?', 'Links do not expire by default. Managed links can have an optional expiration date.'],
  ['What analytics are collected?', '247URL tracks aggregate clicks, referrers, devices, browsers, and optional country data. Raw IP addresses are never stored in analytics records.'],
  ['Can I use my own short domain?', 'The current backend includes deployment support for a separate short domain. Self-service custom-domain verification is not implemented yet.'],
]
const openFaq = ref<number | null>(0)
</script>
<template>
  <div>
    <section class="border-b border-border bg-surface">
      <div class="container-shell pb-20 pt-16 md:pb-24 md:pt-20">
        <div class="mb-8 inline-flex items-center gap-2 rounded-full border border-brand-mid bg-brand-light px-3 py-1.5 text-[11px] font-semibold uppercase tracking-[0.1em] text-brand"><span class="size-1.5 rounded-full bg-brand"/>The simple way to shorten, manage &amp; measure links</div>
        <h1 class="max-w-3xl text-5xl font-bold leading-[1.06] tracking-[-0.035em] sm:text-6xl lg:text-[68px]">Short links.<br><span class="text-brand">Serious results.</span></h1>
        <p class="mt-6 max-w-xl text-base leading-relaxed text-text-secondary md:text-lg">Create branded short links, manage destinations, generate QR codes, and understand every click — all from one simple workspace.</p>
        <div class="mt-9 flex flex-wrap gap-3"><NuxtLink to="/register" class="btn-primary btn-lg">Create a free link</NuxtLink><NuxtLink to="/features" class="btn-secondary btn-lg">Explore features</NuxtLink></div>
        <div class="mt-12 max-w-3xl"><UrlShortenerForm compact/></div>
      </div>
    </section>
    <section class="container-shell py-20">
      <div class="mb-8 flex items-end justify-between gap-4"><div><p class="eyebrow">Product preview</p><h2 class="mt-2 text-3xl font-bold tracking-[-0.025em]">See the full picture behind every link.</h2></div><span class="hidden text-xs text-text-muted sm:block">Illustrative preview</span></div>
      <div class="overflow-hidden rounded-xl border border-border bg-surface shadow-lg"><div class="flex items-center gap-2 border-b border-border bg-canvas px-4 py-3"><span class="size-2 rounded-full bg-red-300"/><span class="size-2 rounded-full bg-amber-300"/><span class="size-2 rounded-full bg-green-300"/><span class="ml-3 text-[10px] text-text-muted">247URL workspace</span></div><div class="grid gap-5 p-5 md:grid-cols-[1.1fr_.9fr] md:p-7"><div><div class="flex flex-wrap items-center gap-3"><span class="text-lg font-bold text-brand">247url.com/summer</span><span class="badge-success"><span class="size-1.5 rounded-full bg-success"/>Active</span></div><p class="mt-1 truncate text-sm text-text-muted">example.com/summer-campaign</p><div class="mt-6 grid grid-cols-2 gap-3"><StatCard label="Clicks" value="12,482"/><StatCard label="Unique visitors" value="8,921" tone="violet"/></div></div><div class="surface p-4"><div class="mb-5 flex items-center justify-between"><div><p class="text-xs font-semibold">Clicks over time</p><p class="text-[10px] text-text-muted">30-day preview</p></div><span class="text-xs font-medium text-success">+18.4%</span></div><svg viewBox="0 0 500 140" class="h-36 w-full" preserveAspectRatio="none" aria-label="Illustrative rising clicks chart"><defs><linearGradient id="home-area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#4F46E5" stop-opacity=".16"/><stop offset="1" stop-color="#4F46E5" stop-opacity="0"/></linearGradient></defs><path d="M0 125 L45 108 L90 115 L135 92 L180 98 L225 66 L270 75 L315 43 L360 55 L405 24 L450 36 L500 12 L500 140 L0 140 Z" fill="url(#home-area)"/><path d="M0 125 L45 108 L90 115 L135 92 L180 98 L225 66 L270 75 L315 43 L360 55 L405 24 L450 36 L500 12" fill="none" stroke="#4F46E5" stroke-width="3" stroke-linecap="round"/></svg></div></div></div>
    </section>
    <section class="border-y border-border bg-surface"><div class="container-shell py-20"><div class="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p class="eyebrow">Built for links that matter</p><h2 class="mt-3 section-title">Quietly powerful infrastructure for everyday campaigns.</h2><p class="mt-4 max-w-md text-text-secondary">A focused toolset with fast redirects, clear controls, and privacy-conscious measurements.</p></div><div class="grid gap-x-10 gap-y-8 sm:grid-cols-2"><div v-for="item in [['Fast redirects','Redis-first resolution with database fallback.'],['Reliable analytics','Queued click processing never delays a valid redirect.'],['Editable destinations','Update where a short link points without replacing it.'],['Privacy-conscious','Daily visitor hashes replace stored raw IP addresses.']]" :key="item[0]" class="border-t border-border pt-4"><span class="mb-3 grid size-8 place-items-center rounded-md bg-brand-light text-brand">↗</span><h3 class="font-semibold">{{ item[0] }}</h3><p class="mt-1 text-sm text-text-secondary">{{ item[1] }}</p></div></div></div></div></section>
    <section class="container-shell py-24"><div class="max-w-xl"><p class="eyebrow">One workspace</p><h2 class="mt-3 section-title">Everything you need to manage modern links.</h2></div><div class="mt-12 grid gap-px overflow-hidden rounded-xl border border-border bg-border md:grid-cols-3"><article v-for="(item, i) in [['Shorten','Create clean, memorable short URLs.'],['Manage','Edit destinations, expiration, tags, and status.'],['Analyze','Understand clicks, devices, referrers, and trends.'],['Share','Generate QR codes for online and offline campaigns.'],['API','Connect secure link workflows to your applications.'],['Domains','Deploy 247URL on the short domain you control.']]" :key="item[0]" class="bg-surface p-6"><span class="text-[10px] font-semibold text-brand">0{{ i + 1 }}</span><h3 class="mt-4 text-base font-semibold">{{ item[0] }}</h3><p class="mt-2 text-sm text-text-secondary">{{ item[1] }}</p></article></div></section>
    <section class="border-y border-border bg-surface"><div class="container-shell grid gap-10 py-20 lg:grid-cols-[.75fr_1.25fr]"><div><p class="eyebrow">Questions</p><h2 class="mt-3 section-title">Frequently asked questions.</h2><p class="mt-4 text-text-secondary">Need something else? <NuxtLink to="/contact" class="text-brand">Contact the team.</NuxtLink></p></div><div class="divide-y divide-border border-y border-border"><div v-for="(faq, i) in faqs" :key="faq[0]"><button type="button" class="flex w-full items-center justify-between gap-4 py-4 text-left text-sm font-medium" :aria-expanded="openFaq === i" @click="openFaq = openFaq === i ? null : i"><span>{{ faq[0] }}</span><span class="text-text-muted">{{ openFaq === i ? '−' : '+' }}</span></button><p v-if="openFaq === i" class="pb-4 text-sm leading-relaxed text-text-secondary">{{ faq[1] }}</p></div></div></div></section>
    <section class="container-shell mt-20"><div class="rounded-xl bg-brand px-6 py-14 text-center text-white sm:px-12"><h2 class="text-3xl font-bold tracking-[-0.025em]">Your next link starts here.</h2><p class="mx-auto mt-3 max-w-lg text-sm text-indigo-100">Create, manage, and understand links from one focused workspace.</p><NuxtLink to="/register" class="btn mt-7 bg-white px-5 text-brand hover:bg-indigo-50">Create your free account</NuxtLink></div></section>
  </div>
</template>
