<script setup lang="ts">
useSeoPage('Sign in', 'Sign in to manage your short links and analytics.', '/login')
const route = useRoute()
const { login } = useAuth()
const form = reactive({ email: '', password: '', remember: false })
const error = ref(''); const errors = ref<Record<string, string[]>>({}); const loading = ref(false)
async function submit() { loading.value = true; error.value = ''; errors.value = {}; try { await login(form); await navigateTo('/dashboard') } catch (e: any) { error.value = e?.data?.message || 'Unable to sign in.'; errors.value = e?.data?.errors || {} } finally { loading.value = false } }
</script>
<template><section class="container-shell py-16"><div class="mx-auto max-w-md"><div class="surface p-7 sm:p-9"><p class="eyebrow">Welcome back</p><h1 class="mt-3 text-3xl font-black">Sign in to 247URL</h1><p v-if="route.query.verified" class="mt-4 rounded-xl bg-teal-300/10 p-3 text-sm text-teal-200">Email verified. You can now use every dashboard feature.</p><form class="mt-7 grid gap-5" @submit.prevent="submit"><div><label class="label" for="email">Email</label><input id="email" v-model="form.email" class="input" type="email" autocomplete="email" required><p class="mt-1 text-sm text-rose-300">{{ errors.email?.[0] }}</p></div><div><div class="flex justify-between"><label class="label" for="password">Password</label><NuxtLink to="/forgot-password" class="text-sm text-teal-300">Forgot password?</NuxtLink></div><input id="password" v-model="form.password" class="input" type="password" autocomplete="current-password" required></div><label class="flex items-center gap-3 text-sm text-slate-300"><input v-model="form.remember" type="checkbox" class="size-4 accent-teal-300">Keep me signed in for 30 days</label><p v-if="error && !Object.keys(errors).length" class="text-sm text-rose-300" role="alert">{{ error }}</p><button class="btn-primary w-full" :disabled="loading">{{ loading ? 'Signing in…' : 'Sign in' }}</button></form><p class="mt-6 text-center text-sm text-slate-400">New here? <NuxtLink to="/register" class="font-semibold text-teal-300">Create an account</NuxtLink></p></div></div></section></template>
