<script setup lang="ts">
useSeoPage('Pricing', 'Clear, configurable 247URL plan options without pretending billing is already connected.', '/pricing')
const yearly = ref(false)
const plans = [
  { name:'Free', price:'$0', suffix:'forever', copy:'For individuals getting started.', features:['Short links','Custom aliases','Basic analytics','QR codes','Link management'], cta:'Get started free', to:'/register', available:true },
  { name:'Pro', price:'$12', suffix:'/ month', copy:'Configurable future hosted plan.', features:['Everything in Free','Advanced analytics','Longer retention','Custom domains','API access'], cta:'Join the waitlist', to:'/contact', featured:true, available:false },
  { name:'Business', price:'Custom', suffix:'', copy:'Planned for teams and organizations.', features:['Everything in Pro','Team management','Advanced permissions','Higher limits','Priority support'], cta:'Contact us', to:'/contact', available:false },
]
</script>
<template><div>
  <section class="border-b border-border bg-surface"><div class="container-shell py-20 text-center"><p class="eyebrow">Simple, transparent pricing</p><h1 class="mx-auto mt-4 max-w-3xl text-5xl font-bold leading-[1.08] tracking-[-0.035em] sm:text-6xl">Choose the plan that<br><span class="text-brand">fits your links.</span></h1><p class="mx-auto mt-5 max-w-xl text-lg text-text-secondary">The self-hosted product is available now. Hosted paid plans are shown as configurable product direction, not active billing.</p><div class="mt-8 inline-flex rounded-md border border-border bg-surface2 p-0.5"><button class="rounded-sm px-4 py-2 text-xs font-medium" :class="!yearly ? 'bg-surface shadow-xs' : 'text-text-muted'" @click="yearly=false">Monthly</button><button class="rounded-sm px-4 py-2 text-xs font-medium" :class="yearly ? 'bg-surface shadow-xs' : 'text-text-muted'" @click="yearly=true">Yearly <span class="text-success">Save 20%</span></button></div></div></section>
  <section class="container-shell py-16"><div class="grid gap-5 lg:grid-cols-3"><article v-for="plan in plans" :key="plan.name" class="relative rounded-xl border bg-surface p-6 shadow-xs" :class="plan.featured ? 'border-brand' : 'border-border'"><span v-if="plan.featured" class="absolute right-5 top-5 badge-brand">Planned</span><h2 class="text-base font-semibold">{{ plan.name }}</h2><div class="mt-5 flex items-end gap-2"><span class="text-4xl font-bold tracking-[-0.03em]">{{ plan.price }}</span><span class="pb-1 text-sm text-text-muted">{{ plan.suffix }}</span></div><p class="mt-3 min-h-11 text-sm text-text-secondary">{{ plan.copy }}</p><NuxtLink :to="plan.to" class="mt-6 w-full" :class="plan.featured ? 'btn-primary' : 'btn-secondary'">{{ plan.cta }}</NuxtLink><p v-if="!plan.available" class="mt-2 text-center text-[10px] text-warning">Billing and entitlement enforcement are not connected.</p><ul class="mt-6 grid gap-3 border-t border-border pt-5 text-sm text-text-secondary"><li v-for="feature in plan.features" :key="feature" class="flex gap-2"><span class="text-success">✓</span>{{ feature }}</li></ul></article></div>
    <div class="mt-16"><h2 class="section-title text-center">Everything you need to run links at scale.</h2><div class="mt-8 overflow-x-auto rounded-lg border border-border bg-surface"><table class="w-full min-w-[640px] text-left text-sm"><thead class="bg-canvas text-xs text-text-muted"><tr><th class="p-4">Capability</th><th class="p-4">Free</th><th class="p-4">Pro (planned)</th><th class="p-4">Business (planned)</th></tr></thead><tbody class="divide-y divide-border"><tr v-for="row in [['Short links','✓','✓','✓'],['Custom aliases','✓','✓','✓'],['Analytics','Basic','Advanced','Advanced'],['QR codes','✓','✓','✓'],['API access','✓','✓','✓'],['Custom domains','Deploy config','Self-service','Self-service'],['Team members','—','—','Planned'],['Billing','Not required','Not connected','Not connected']]" :key="row[0]"><td class="p-4 font-medium">{{ row[0] }}</td><td class="p-4 text-text-secondary">{{ row[1] }}</td><td class="p-4 text-text-secondary">{{ row[2] }}</td><td class="p-4 text-text-secondary">{{ row[3] }}</td></tr></tbody></table></div></div>
  </section>
  <section class="container-shell"><div class="rounded-xl bg-brand px-6 py-14 text-center text-white"><h2 class="text-3xl font-bold">Start with the basics. Scale when you need to.</h2><p class="mt-3 text-indigo-100">No payment workflow is required to use the current self-hosted release.</p><div class="mt-7 flex justify-center gap-3"><NuxtLink to="/register" class="btn bg-white text-brand">Create free account</NuxtLink><NuxtLink to="/contact" class="btn border border-white/30 text-white">Talk to us</NuxtLink></div></div></section>
</div></template>
