<script setup lang="ts">
import type { LinkRecord } from '~/types/api'
import { reactive } from 'vue'
const props = defineProps<{ link?: LinkRecord; submitLabel?: string }>()
const emit = defineEmits<{ submit: [payload: Record<string, unknown>] }>()
const form = reactive({ destination_url: props.link?.destination_url || '', custom_alias: props.link?.custom_alias || '', title: props.link?.title || '', description: props.link?.description || '', expires_at: props.link?.expires_at?.slice(0, 16) || '', is_active: props.link?.is_active ?? true, tags: props.link?.tags?.join(', ') || '' })
function submit() { emit('submit', { ...form, custom_alias: form.custom_alias || null, expires_at: form.expires_at || null, tags: form.tags.split(',').map(v => v.trim()).filter(Boolean) }) }
</script>
<template><form class="surface grid gap-6 p-6 sm:p-8" @submit.prevent="submit"><div><label class="label" for="destination">Destination URL</label><input id="destination" v-model="form.destination_url" class="input" type="url" required></div><div class="grid gap-5 sm:grid-cols-2"><div><label class="label" for="alias">Custom alias</label><input id="alias" v-model="form.custom_alias" class="input" pattern="[A-Za-z0-9_-]+" minlength="3" maxlength="64" placeholder="campaign-name"></div><div><label class="label" for="expires">Expiration</label><input id="expires" v-model="form.expires_at" class="input" type="datetime-local"></div></div><div><label class="label" for="title">Title</label><input id="title" v-model="form.title" class="input" maxlength="160"></div><div><label class="label" for="description">Description</label><textarea id="description" v-model="form.description" class="input min-h-28" maxlength="2000" /></div><div><label class="label" for="tags">Tags</label><input id="tags" v-model="form.tags" class="input" placeholder="campaign, social, launch"><p class="mt-2 text-xs text-slate-500">Separate up to 10 tags with commas.</p></div><label class="flex items-center gap-3"><input v-model="form.is_active" type="checkbox" class="size-5 accent-teal-300"><span class="font-semibold">Link is active</span></label><button class="btn-primary w-fit">{{ submitLabel || 'Save link' }}</button></form></template>
