export interface ResourceArticle { slug: string; category: string; title: string; description: string; readTime: string; date: string; sections: Array<{ heading: string; paragraphs: string[]; bullets?: string[] }> }
const resourceArticles: ResourceArticle[] = [
  { slug:'link-tracking-strategy', category:'Guides', title:'How to build a better link tracking strategy', description:'A practical guide to understanding clicks, referrers, campaigns, and analytics without overcomplicating your workflow.', readTime:'8 min read', date:'Sep 21, 2026', sections:[{ heading:'Start with a question', paragraphs:['Useful tracking begins with a decision you need to make. Define the campaign, channel, and outcome before creating links.'], bullets:['Use one canonical destination','Choose consistent campaign names','Document who owns the link']},{ heading:'Keep links stable', paragraphs:['A short link should be the stable public address. Update its destination when a campaign changes instead of printing or publishing a second short code.']},{ heading:'Read trends in context', paragraphs:['Clicks and unique visitors describe different things. Compare date ranges, referrers, and device context before drawing conclusions from a single total.']}] },
  { slug:'how-url-shorteners-work', category:'Guides', title:'How URL shorteners work', description:'A practical explanation of short codes, redirects, analytics, and link management.', readTime:'6 min read', date:'Sep 18, 2026', sections:[{ heading:'A short code is a lookup key', paragraphs:['The short code maps to a destination record. In 247URL it is case-sensitive and resolved from Redis first, with MySQL as the durable source of truth.']},{ heading:'Why 302 redirects matter', paragraphs:['A temporary redirect lets an owner update the destination without clients permanently caching an older target. Query strings supplied on the short URL are preserved.']},{ heading:'Analytics should not block', paragraphs:['247URL queues a privacy-conscious click event after resolving the destination. A queue failure may lose analytics, but it must not make a valid link fail.']}] },
  { slug:'api-getting-started', category:'API', title:'Getting started with the 247URL API', description:'Create scoped tokens and make your first authenticated link request.', readTime:'7 min read', date:'Sep 17, 2026', sections:[{ heading:'Create a token', paragraphs:['Create an API token from the dashboard. Copy it during the one-time creation window and store it in a secret manager.']},{ heading:'Send an authenticated request', paragraphs:['Send the token as a Bearer credential to the versioned API. Tokens can read and write links and read analytics; they cannot manage the account or mint other tokens.']},{ heading:'Handle errors', paragraphs:['Validation uses HTTP 422 with field-keyed errors. Treat 401, 403, 404, 410, and 429 according to their standard meanings.']}] },
  { slug:'utm-parameters-explained', category:'Analytics', title:'UTM parameters explained', description:'Use consistent campaign parameters without turning reporting into busywork.', readTime:'5 min read', date:'Sep 14, 2026', sections:[{ heading:'Use a small vocabulary', paragraphs:['Pick stable values for source, medium, and campaign. Consistency makes grouped reporting more reliable than highly specific one-off labels.']},{ heading:'Preserve the destination', paragraphs:['247URL stores the full destination including its query string. The redirect also preserves query parameters added to the short URL.']}] },
  { slug:'understanding-click-analytics', category:'Analytics', title:'Understanding click analytics', description:'Read clicks, unique visitors, referrers, devices, and country aggregates responsibly.', readTime:'8 min read', date:'Sep 11, 2026', sections:[{ heading:'Clicks are events', paragraphs:['A person can click more than once. Total clicks describe traffic volume, not a count of people.']},{ heading:'Unique counts are privacy-conscious estimates', paragraphs:['247URL uses keyed daily visitor hashes and does not persist raw IP addresses. Unique totals are daily aggregates, not durable person profiles.']}] },
  { slug:'link-security', category:'Security', title:'How we approach link security', description:'URL validation, rate limits, ownership checks, and abuse controls in the current architecture.', readTime:'9 min read', date:'Sep 9, 2026', sections:[{ heading:'Validate without fetching', paragraphs:['Submitted destinations are restricted to HTTP and HTTPS and checked for malformed hosts, credentials, and configured block lists. Normal shortening does not fetch the destination, avoiding a server-side request forgery path.']},{ heading:'Enforce ownership', paragraphs:['Laravel policies scope link reads and mutations to the owner. API tokens have explicit abilities and expire.']},{ heading:'Control abuse', paragraphs:['Anonymous creation, authenticated creation, analytics, authentication, password reset, and abuse reporting use separate configurable rate limits.']}] },
]
export function useResources() { return { resources: resourceArticles, findResource: (slug: string) => resourceArticles.find(item => item.slug === slug) } }
