<script setup lang="ts">
import type { ApiEnvelope, LinkRecord } from '~/types/api'
definePageMeta({ layout: 'dashboard', middleware: 'auth' })
const route = useRoute(); const period = ref('30d')
interface Analytics { period: string; total_clicks: number; unique_clicks: number; timeline: Array<{ date: string; clicks: number; unique_clicks: number }>; referrers: Array<{ label: string; value: number }>; countries: Array<{ label: string; value: number }>; devices: Array<{ label: string; value: number }>; browsers: Array<{ label: string; value: number }> }
const { data: link } = await useFetch<ApiEnvelope<LinkRecord>>(`/api/backend/links/${route.params.id}`)
const { data, pending } = await useFetch<ApiEnvelope<Analytics>>(() => `/api/backend/links/${route.params.id}/analytics`, { query: computed(() => ({ period: period.value })), watch: [period] })
useSeoPage('Link analytics', 'Click trends and audience aggregates for your link.', `/dashboard/links/${route.params.id}/analytics`)
</script>
<template><div><NuxtLink :to="`/dashboard/links/${route.params.id}`" class="text-sm text-teal-300">← Back to link</NuxtLink><div class="mt-4 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="eyebrow">Analytics</p><h1 class="mt-2 text-3xl font-black">{{ link?.data.title || link?.data.short_code || 'Link performance' }}</h1></div><select v-model="period" class="input max-w-40" aria-label="Analytics period"><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option><option value="90d">Last 90 days</option></select></div><LoadingState v-if="pending" class="mt-8"/><template v-else-if="data"><div class="mt-8 grid gap-4 sm:grid-cols-2"><StatCard label="Total clicks" :value="data.data.total_clicks.toLocaleString()" :detail="`During the selected ${data.data.period} period`"/><StatCard label="Unique clicks" :value="data.data.unique_clicks.toLocaleString()" detail="Privacy-safe daily estimate"/></div><AnalyticsChart class="mt-6" :points="data.data.timeline"/><div class="mt-6 grid gap-5 md:grid-cols-2 xl:grid-cols-4"><section v-for="section in [{ title: 'Referrers', rows: data.data.referrers }, { title: 'Countries', rows: data.data.countries }, { title: 'Devices', rows: data.data.devices }, { title: 'Browsers', rows: data.data.browsers }]" :key="section.title" class="surface p-5"><h2 class="font-bold">{{ section.title }}</h2><div class="mt-4 grid gap-3"><div v-for="row in section.rows" :key="row.label" class="flex justify-between gap-4 text-sm"><span class="truncate text-slate-400">{{ row.label }}</span><strong>{{ row.value }}</strong></div><p v-if="!section.rows.length" class="text-sm text-slate-500">No data yet.</p></div></section></div></template></div></template>
