<script setup lang="ts">
definePageMeta({layout:'dashboard',middleware:'auth'});useSeoPage('API tokens','Create and revoke scoped 247URL API tokens.','/dashboard/api')
interface Token{id:number;name:string;last_used_at:string|null;expires_at:string|null;created_at:string}
const {request}=useApi();const tokens=ref<Token[]>([]);const name=ref('');const newToken=ref('');const error=ref('');const loading=ref(false);const {show}=useToast()
const format=(value:string|null)=>value?new Intl.DateTimeFormat('en',{dateStyle:'medium'}).format(new Date(value)):'Never'
async function load(){loading.value=true;error.value='';try{tokens.value=(await request<{data:Token[]}>('api-tokens')).data}catch(e:any){error.value=e?.data?.message||'Unable to load API tokens.'}finally{loading.value=false}}
async function createToken(){error.value='';try{const response=await request<{data:{token:string}}>('api-tokens',{method:'POST',body:{name:name.value,expires_in_days:90}});newToken.value=response.data.token;name.value='';show('API token created. Copy it now.');await load()}catch(e:any){error.value=e?.data?.errors?.name?.[0]||e?.data?.message||'Unable to create token.'}}
async function revoke(id:number){if(!confirm('Revoke this API token? Integrations using it will stop immediately.'))return;await request(`api-tokens/${id}`,{method:'DELETE'});show('API token revoked.');await load()}
onMounted(load)
</script>
<template><div class="dashboard-page max-w-[900px]"><div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><h1 class="page-title">API</h1><p class="mt-1 text-sm text-text-secondary">Use expiring, scoped tokens for direct API integrations.</p></div><a href="/resources/api-getting-started" class="btn-secondary">Read API guide</a></div><section class="surface mt-7 p-5 sm:p-6"><h2 class="text-sm font-semibold">Create API token</h2><p class="mt-1 text-xs text-text-muted">Tokens expire after 90 days and can manage links and read analytics. Store them in a secret manager.</p><form class="mt-5 flex flex-col gap-3 sm:flex-row" @submit.prevent="createToken"><label class="flex-1"><span class="sr-only">Token name</span><input v-model="name" class="input" required maxlength="100" placeholder="Production integration"></label><button class="btn-primary">Create token</button></form><div v-if="newToken" class="mt-5 rounded-lg border border-warning-border bg-warning-bg p-4"><p class="text-sm font-semibold text-warning">Copy this token now. It will not be shown again.</p><code class="mt-3 block break-all rounded-md bg-white p-3 text-xs text-text-primary">{{ newToken }}</code><CopyButton class="mt-3" :text="newToken" label="Copy token"/></div><p v-if="error" class="mt-4 field-error" role="alert">{{ error }}</p></section><section class="mt-5"><div class="mb-3 flex items-center justify-between"><h2 class="text-sm font-semibold">Active tokens</h2><span class="text-xs text-text-muted">{{ tokens.length }} total</span></div><LoadingState v-if="loading" :rows="2"/><EmptyState v-else-if="!tokens.length" title="No API tokens yet" message="Create a token when an application needs direct API access."/><div v-else class="surface overflow-hidden"><div v-for="token in tokens" :key="token.id" class="flex flex-col gap-3 border-b border-border p-5 last:border-0 sm:flex-row sm:items-center"><div class="min-w-0 flex-1"><p class="text-sm font-medium">{{ token.name }}</p><p class="mt-1 text-xs text-text-muted">Created {{ format(token.created_at) }} · Last used {{ format(token.last_used_at) }} · Expires {{ format(token.expires_at) }}</p></div><button class="btn-danger h-8 text-xs" @click="revoke(token.id)">Revoke</button></div></div></section></div></template>
