<script setup lang="ts">
definePageMeta({ layout: 'dashboard', middleware: 'auth' }); useSeoPage('Settings', 'Manage API access for your 247URL account.', '/dashboard/settings')
interface Token { id: number; name: string; last_used_at: string | null; expires_at: string | null; created_at: string }
const { request } = useApi(); const tokens = ref<Token[]>([]); const name = ref(''); const newToken = ref(''); const error = ref('')
async function load() { try { tokens.value = (await request<{ data: Token[] }>('api-tokens')).data } catch (e: any) { error.value = e?.data?.message || 'Unable to load API tokens.' } }
async function createToken() { try { const response = await request<{ data: { token: string } }>('api-tokens', { method: 'POST', body: { name: name.value, expires_in_days: 90 } }); newToken.value = response.data.token; name.value = ''; await load() } catch (e: any) { error.value = e?.data?.errors?.name?.[0] || e?.data?.message } }
async function revoke(id: number) { if (confirm('Revoke this API token?')) { await request(`api-tokens/${id}`, { method: 'DELETE' }); await load() } }
onMounted(load)
</script>
<template><div class="max-w-4xl"><p class="eyebrow">Workspace</p><h1 class="mt-2 text-3xl font-black">Settings</h1><section class="surface mt-8 p-6"><h2 class="text-xl font-bold">API tokens</h2><p class="mt-2 text-sm text-slate-400">Tokens are scoped to links and analytics and expire after 90 days. Store them in a secret manager.</p><form class="mt-6 flex flex-col gap-3 sm:flex-row" @submit.prevent="createToken"><label class="flex-1"><span class="sr-only">Token name</span><input v-model="name" class="input" required maxlength="100" placeholder="Production integration"></label><button class="btn-primary">Create token</button></form><div v-if="newToken" class="mt-5 rounded-xl border border-teal-300/30 bg-teal-300/5 p-4"><p class="font-bold text-teal-200">Copy this token now. It will not be shown again.</p><code class="mt-3 block break-all text-sm">{{ newToken }}</code><CopyButton class="mt-4" :text="newToken"/></div><p v-if="error" class="mt-4 text-rose-300">{{ error }}</p><div class="mt-6 divide-y divide-white/10"><div v-for="token in tokens" :key="token.id" class="flex items-center justify-between gap-4 py-4"><div><p class="font-semibold">{{ token.name }}</p><p class="text-xs text-slate-500">Created {{ new Date(token.created_at).toLocaleDateString() }} · Last used {{ token.last_used_at ? new Date(token.last_used_at).toLocaleDateString() : 'never' }}</p></div><button class="btn-secondary text-rose-300" @click="revoke(token.id)">Revoke</button></div><p v-if="!tokens.length" class="py-6 text-sm text-slate-500">No API tokens yet.</p></div></section><section class="surface mt-6 p-6"><h2 class="text-xl font-bold">Billing foundation</h2><p class="mt-2 text-slate-400">Accounts and usage data are separated from plan rules so billing can be added without changing link ownership or redirect behavior. No paid plan is enabled in this release.</p></section></div></template>
