<script setup lang="ts">
import QrcodeVue from'qrcode.vue'
import { ref } from 'vue'
import type { LinkRecord } from '~/types/api'
definePageMeta({layout:'dashboard',middleware:'auth'});useSeoPage('Create link','Create a new managed short link.','/dashboard/links/create')
const{create}=useLinks();const error=ref('');const loading=ref(false);const created=ref<LinkRecord|null>(null);const showQr=ref(false)
async function submit(payload:Record<string,unknown>){loading.value=true;error.value='';try{const response=await create(payload);created.value=response.data}catch(e:any){error.value=Object.values(e?.data?.errors||{}).flat().join(' ')||e?.data?.message||'Unable to create link.'}finally{loading.value=false}}
</script>
<template><div class="dashboard-page"><NuxtLink to="/dashboard/links" class="text-xs text-text-muted hover:text-brand">← Back to links</NuxtLink><div class="mt-4"><h1 class="page-title">Create a short link</h1><p class="mt-1 text-sm text-text-secondary">Paste a URL to create a link saved to your account.</p></div><p v-if="error" class="mt-5 rounded-lg border border-danger-border bg-danger-bg p-4 text-sm text-danger" role="alert">{{ error }}</p><div class="mt-6 max-w-[680px]"><LinkForm v-if="!created" simple-create submit-label="Create short link" :loading="loading" @submit="submit"/><section v-else class="surface p-5 sm:p-6" aria-live="polite"><h2 class="text-lg font-semibold text-success">✓ Short link created!</h2><p class="mt-1 text-sm text-text-secondary">Saved to your links.</p><a :href="created.short_url" target="_blank" rel="noopener noreferrer" class="mt-4 block break-all text-base font-semibold text-brand">{{ created.short_url }}</a><div class="mt-4 flex flex-wrap gap-2"><CopyButton :text="created.short_url"/><button type="button" class="btn-secondary h-8 px-3 text-xs" @click="showQr=!showQr">{{ showQr ? 'Hide QR code' : 'QR code' }}</button><NuxtLink :to="`/dashboard/links/${created.id}`" class="btn-secondary h-8 px-3 text-xs">View link</NuxtLink><NuxtLink :to="`/dashboard/links/${created.id}/analytics`" class="btn-secondary h-8 px-3 text-xs">Analytics</NuxtLink></div><div v-if="showQr" class="mt-4 inline-block rounded-md border border-border bg-white p-3"><QrcodeVue :value="created.short_url" :size="160" level="M" render-as="svg"/></div><button type="button" class="mt-5 block text-xs font-medium text-brand" @click="created=null;showQr=false">Create another link</button></section></div></div></template>
