<script setup lang="ts">
import type { LinkRecord } from '~/types/api'
definePageMeta({ layout: 'dashboard', middleware: 'auth' })
useSeoPage('Links', 'Search, filter, and manage your short links.', '/dashboard/links')
const { links, meta, loading, list, update, remove } = useLinks(); const search = ref(''); const status = ref(''); const sort = ref('created_at'); const page = ref(1); const error = ref('')
async function load() { try { await list({ search: search.value, status: status.value, sort: sort.value, page: page.value }) } catch (e: any) { error.value = e?.data?.message || 'Unable to load links.' } }
async function toggle(link: LinkRecord) { await update(link.id, { is_active: !link.is_active }); await load() }
async function destroy(link: LinkRecord) { if (confirm(`Delete ${link.short_url}? This cannot be undone.`)) { await remove(link.id); await load() } }
watch([status, sort, page], load); let timer: ReturnType<typeof setTimeout>; watch(search, () => { clearTimeout(timer); timer = setTimeout(load, 300) }); onMounted(load)
</script>
<template><div><div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="eyebrow">Library</p><h1 class="mt-2 text-3xl font-black">Links</h1><p class="mt-2 text-slate-400">Search destinations, inspect performance, and control availability.</p></div><NuxtLink to="/dashboard/links/create" class="btn-primary">Create link</NuxtLink></div><div class="mt-8 grid gap-3 md:grid-cols-[1fr_12rem_12rem]"><label><span class="sr-only">Search links</span><input v-model="search" class="input" type="search" placeholder="Search links"></label><select v-model="status" class="input" aria-label="Filter by status"><option value="">All statuses</option><option value="active">Active</option><option value="disabled">Disabled</option><option value="expired">Expired</option></select><select v-model="sort" class="input" aria-label="Sort links"><option value="created_at">Newest</option><option value="clicks_count">Most clicks</option><option value="title">Title</option><option value="expires_at">Expiration</option></select></div><LoadingState v-if="loading" class="mt-6"/><p v-else-if="error" class="mt-6 text-rose-300">{{ error }}</p><EmptyState v-else-if="!links.length" class="mt-6" title="No links found" message="Create your first short link or clear the current filters."><NuxtLink to="/dashboard/links/create" class="btn-primary">Create link</NuxtLink></EmptyState><LinkTable v-else class="mt-6" :links="links" @toggle="toggle" @delete="destroy"/><nav v-if="meta && meta.last_page > 1" class="mt-6 flex items-center justify-between" aria-label="Pagination"><button class="btn-secondary" :disabled="page <= 1" @click="page--">Previous</button><span class="text-sm text-slate-400">Page {{ meta.current_page }} of {{ meta.last_page }}</span><button class="btn-secondary" :disabled="page >= meta.last_page" @click="page++">Next</button></nav></div></template>
